# Load The Dataset

In [1]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("Datasets/Titanic-Dataset.csv",usecols = ['Survived','Pclass','Sex','Age','SibSp','Parch','Fare','Embarked'])
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [36]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [37]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [38]:
x = df.drop(columns = ['Survived'])
y = df['Survived']
x.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [39]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)
print(X_train.shape,X_test.shape)

(712, 7) (179, 7)


#### Goal 
### -->  imupte missing values in age and Embarked column with mode
### --> apply standard Scaler on Age and Fare column
### --> apply one hot encoding on sex and embarked column

# Without using Column Transformer

In [40]:
from sklearn.impute import SimpleImputer
si_num = SimpleImputer(strategy="mean")
X_train_AgeFare = si_num.fit_transform(X_train[['Age','Fare']])
X_test_AgeFare = si_num.transform(X_test[['Age','Fare']])
X_train_AgeFare.shape

(712, 2)

In [41]:
si_cat = SimpleImputer(strategy="most_frequent")
X_train_SexEmbarked = si_cat.fit_transform(X_train[['Sex','Embarked']])
X_test_SexEmbarked = si_cat.transform(X_test[['Sex','Embarked']])
X_train_SexEmbarked.shape

(712, 2)

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_AgeFare_sc = sc.fit_transform(X_train_AgeFare)
X_test_AgeFare_sc = sc.transform(X_test_AgeFare)
X_train_AgeFare_sc.shape

(712, 2)

In [43]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first',sparse_output = False,dtype = 'int32')
X_train_sexEmbarked = ohe.fit_transform(X_train_SexEmbarked)
X_test_sexEmbarked = ohe.transform(X_test_SexEmbarked)
X_train_sexEmbarked

array([[0, 0, 0],
       [1, 0, 1],
       [1, 0, 0],
       ...,
       [1, 1, 0],
       [0, 0, 1],
       [1, 0, 1]], dtype=int32)

In [44]:
x_train_transformed = np.concatenate((X_train_AgeFare,X_train_sexEmbarked),axis = 1)
x_test_transformed = np.concatenate((X_test_AgeFare,X_test_sexEmbarked),axis = 1)

In [45]:
x_train_transformed.shape

(712, 5)

In [46]:
x_test_transformed.shape

(179, 5)

# Using Column Transformer and Pipeline

In [48]:
X_train.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
140       3  female   NaN      0      2  15.2458        C
439       2    male  31.0      0      0  10.5000        S
817       2    male  31.0      1      1  37.0042        C
378       3    male  20.0      0      0   4.0125        C
491       3    male  21.0      0      0   7.2500        S

In [49]:
X_test.head()

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
495       3    male   NaN      0      0   14.4583        C
648       3    male   NaN      0      0    7.5500        S
278       3    male   7.0      4      1   29.1250        Q
31        1  female   NaN      1      0  146.5208        C
255       3  female  29.0      0      2   15.2458        C

In [50]:
y_train.head()

140    0
439    0
817    0
378    0
491    0
Name: Survived, dtype: int64

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier


In [61]:
# imputation transformer
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [62]:
# one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [63]:

# Scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [64]:
# Feature selection
trf4 = SelectKBest(score_func=chi2,k=8)

In [65]:

# train the model
trf5 = DecisionTreeClassifier()

In [66]:
pipe = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [67]:
# pipe = make_pipeline(trf1,trf2,trf3,trf4,trf5) 

In [68]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x000001E3C743D120>)),
                ('trf5', DecisionTreeClassifier())])

In [69]:
pipe.named_steps


{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'trf4': SelectKBest(k=8, score_func=<function chi2 at 0x000001E3C743D120>),
 'trf5': DecisionTreeClassifier()}

In [81]:
pipe.named_steps['trf1'].transformers_[0][1].statistics_

array([29.74518389])

In [82]:
pipe.named_steps['trf1'].transformers_[1][1].statistics_

array(['S'], dtype=object)

In [70]:
from sklearn import set_config
set_config(display='diagram')

In [71]:
y_pred = pipe.predict(X_test)


In [72]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0])

In [73]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6759776536312849

# Cross Validation using Pipeline


In [74]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='accuracy').mean()

np.float64(0.6152171771890081)

# GridSearch using Pipeline

In [75]:
# gridsearchcv
params = {
    'trf5__max_depth':[1,2,3,4,5,None]
}

In [76]:

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x000001E3C743D120>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='accuracy')

In [77]:
grid.best_score_


np.float64(0.6152171771890081)

In [78]:
grid.best_params_


{'trf5__max_depth': 5}